import type { Metadata } from 'next'
import { Inter, Lora } from 'next/font/google'

import { QueryWrapper } from '@/components/shared/wrappers/query-wrapper/query-wrapper'

import '@/styles/globals.scss'

import { Footer, Header, ThemeWrapper } from '@/components'
import { getAllCategories } from '@/utils/lib/queries'

const interSans = Inter({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const loraMono = Lora({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const allCategories = await getAllCategories()
  return (
    <html lang='en'>
      <body className={`${interSans.variable} ${loraMono.variable}`}>
        <ThemeWrapper>
          <QueryWrapper>
            <div className='wrapper' id='wrapper'>
              <Header allCategories={allCategories} />
              <main>{children}</main>
              <Footer />
            </div>
          </QueryWrapper>
        </ThemeWrapper>
      </body>
    </html>
  )
}
