import type { Metadata } from 'next'
import { Inter, Lora } from 'next/font/google'

import '@/styles/globals.scss'

const interSans = Inter({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const loraMono = Lora({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${interSans.variable} ${loraMono.variable}`}>{children}</body>
    </html>
  )
}
