import type { Metadata } from 'next'
import { Inter, Lora } from 'next/font/google'

import { QueryWrapper } from '@/components/shared/wrappers/query-wrapper/query-wrapper'

import '@/styles/globals.scss'

import { Footer, Header, ThemeWrapper } from '@/components'
import { getActiveProducts, getCategories } from '@/utils/lib/queries'

const interSans = Inter({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const loraMono = Lora({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const allCategories = await getCategories()
  const activeProducts = await getActiveProducts()

  const searchData: ISearchData = {
    categories: allCategories.map(category => ({
      id: category.id,
      name: category.name,
    })),
    subcategories: allCategories
      .map(category =>
        category.subcategories.map(subcategory => ({
          id: subcategory.id,
          name: subcategory.name,
          categoryName: category.name,
        })),
      )
      .flat(),
    products: activeProducts.map(product => ({
      id: product.id,
      name: product.name,
    })),
  }

  return (
    <html lang='en'>
      <body className={`${interSans.variable} ${loraMono.variable}`}>
        <ThemeWrapper>
          <QueryWrapper>
            <div className='wrapper' id='wrapper'>
              <Header allCategories={allCategories} searchData={searchData} />
              <main>{children}</main>
              <Footer />
            </div>
          </QueryWrapper>
        </ThemeWrapper>
      </body>
    </html>
  )
}
