export const LINKS = {
  Home: '/',
  SingIn: '/sign-in',
  SingUp: '/sign-up',
  Delivery: '/delivery',
  Payment: '/payment',
  ReturnProduct: '/return-product',
  RulesAndConditions: '/rules-and-conditions',
  PrivacyPolicy: '/privacy-policy',
  Categories: '/categories',
  AboutUs: '/about-us',
  CreateProduct: '/create-product',
  UpdateProduct: '/update-product',
  Profile: '/profile',
  Order: '/order',
  Product: '/product',
  Admin: '/admin',
}
